Fixed Build & Detekt Errors (#1715)

diff --git a/.github/workflows/master_dev_ci.yml b/.github/workflows/master_dev_ci.yml
--- a/.github/workflows/master_dev_ci.yml
+++ b/.github/workflows/master_dev_ci.yml
@@ -29,6 +29,18 @@ jobs:
       - name: Change gradlew Permission
         run: chmod +x gradlew
 
+      - name: Check Dependency Guard
+        id: dependencyguard_verify
+        continue-on-error: true
+        run: ./gradlew dependencyGuard
+
+      - name: Prevent updating Dependency Guard baselines if this is a fork
+        id: checkfork_dependencyguard
+        continue-on-error: false
+        if: steps.dependencyguard_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Dependency Guard failed, please update baselines with: ./gradlew dependencyGuardBaseline" && exit 1
+
         # Build App
       - name: Build with Gradle
         run: ./gradlew assemble
